# Generated by Django 3.2.9 on 2021-12-18 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='date_posted',
            new_name='time_created',
        ),
        migrations.AddField(
            model_name='review',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.ticket'),
        ),
    ]
