# Generated by Django 3.2.9 on 2021-12-15 19:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0004_post_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Review',
        ),
    ]
